tabWidth: 2
printWidth: 100
useTabs: false
singleQuote: true
semi: true
bracketSpacing: true
arrowParens: "avoid"
trailingComma: es5
bracketSameLine: true
plugins:
  - "@trivago/prettier-plugin-sort-imports"
importOrder:
  - "^([a-zA-Z].*(?<!\\.(c|le|sc)ss))$"
  - "^(@.*(?<!\\.(c|le|sc)ss))$"
  - "^[./].*(?<!\\.(c|le|sc)ss)$"
  - "\\.(c|le|sc)ss$"
importOrderSeparation: false
importOrderSortSpecifiers: true
